---

###########
# Removed #
###########

manala_deploy_removed:
  - web/app_dev.php
  - web/app_test.php

#########
# Tasks #
#########

manala_deploy_tasks__main:
  - make: install@prod
  - make: build@prod
