---

- hosts: all
  vars:
    # App
    app: "{{ manala_skeleton_options.app }}"
    # Manala
    manala_skeleton:     elao_app_php
    manala_skeleton_env: "{{ env }}"
    manala_skeleton_options_hashes:
      - app_options
      - app_options_env
    manala_skeleton_patterns_hashes:
      - app_patterns
      - app_patterns_env
  roles:
    - manala.skeleton
